### ISSUE TITLE
코드리뷰 

### ISSUE THREAD

**Issue by DongHyunKIM-Hi** [guswlsdl0121/reboot-firstcome#30]
Order 관련해서 코드 개선 점에 대해서 문의 하셨는데 일단 구조적으로 구현에는 문제는 없어 보여요. 
근대 구조를 잘 생각해야 하는게 결국에는 각각의 도메인별로 찢어서 관리한다고 쳤을 때  orderService는 orderController를 통해서 요청이 들어오고 필요한 정보를 묶어서 (여러 모듈의 도메인 정보) 사용자가 원하는 정보를 제공해주는 역할을 담당합니다. 그럼 orderService에서 다루는 order 영역도 다른 모듈에서 가져오는 것 처럼 깔끔하게 가져오는 것이 좋을 것 같아요. 현재는 order 도메인에서 정보를 가져올 때 너무 많은 의존을 service 레벨에서 가지고 있어요.
    private final OrderReader orderReader;
    private final OrderFinder orderFinder;
    private final OrderAppender orderAppender;
    private final OrderValidator orderValidator;
    private final OrderModifier orderModifier;

이런 order 관련된 친구들을 파사드 패턴 혹은 orderuilts? 같은 어떤 하나로 묶고 service 레벨에서는 모든 도메인 정보에 대해서 깔끔하게 가져오게 하는게 더 좋을 것 같아요.

private final Order
private final  Delivery
private final  Settlement
private final  어떤 모듈이든지

이렇게 설계를 해야 이후 확장성이나 운영하는데 있어서 더 편리할 것 같습니다. order의 로직 자체 혹은 정책이 바뀌지 않는 이상 orderService 하위의 모듈에 접근할 필요가 없으니 이를 코드 레벨에서도 반영해주는 것입니다. 

redis에 캐시 매니저라는 친구도 있는데 이걸 사용하면 직접 cachehit cachemiss에 대해서 관리할 필요가 없어요.

이것 외에는 잘 작성되어 있는 것 같습니다.

여기서 좀 더 성능 개선을 위해서 고려할 수 있는 인사이트를 공유 드리겠습니다. redis가 빠르긴 하지만 결국 이건 외부 통신을 해야 해요.
그래서 진짜 성능을 극단적으로 올리기 위해서는 로컬 캐시와 레디스 캐시를 같이 사용하는 경우도 있어요.
ex)
로컬 캐시 조회 없으면 -> redis 캐시 조회 없으면 -> DB 조회
로컬 캐시는 내부 통신, redis는 외부 네트워크 통신

여기서 조심해야 할것은 서버가 여러개면 1번 서버의 로컬 캐시와, 2번 서버의 로컬 캐시가 다른 경우가 발생함 
이를 해결하기 위해서 redis 캐시가 변경되면 알려주는 redis pub/sub 기능을 통한 동기화, 혹은 ttl을 통한 주기적인 동기화 사용

**Comment by guswlsdl0121** [comment]
감사합니다! 추후 구현에서 참고하도록 하겠습니다!
